// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0uBrn35qv7t1rPr0n2zx46ak5qiw0LA',
    appId: '1:351853459724:android:ea2bad0a8de7f89360b129',
    messagingSenderId: '351853459724',
    projectId: 'project-518da',
    storageBucket: 'project-518da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiAFTp4ZF7yV_SCTIv_UIc3v0gwXygLa8',
    appId: '1:351853459724:ios:9eee653270b39db260b129',
    messagingSenderId: '351853459724',
    projectId: 'project-518da',
    storageBucket: 'project-518da.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiAFTp4ZF7yV_SCTIv_UIc3v0gwXygLa8',
    appId: '1:351853459724:ios:9eee653270b39db260b129',
    messagingSenderId: '351853459724',
    projectId: 'project-518da',
    storageBucket: 'project-518da.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
